spring:
  jpa:
    hibernate.ddl-auto: none
    open-in-view: true
  application:
    flyway:
      enabled: true

management:
  endpoints.web.exposure.include: '*'
  endpoint.health.show.details: always
  metrics.export.prometheus.enabled: true

---
spring:
  config.activate.on-profile: local
  security:
    oauth2:
      client:
        registration:
          portalasig_engine:
            client-id: portalasig_engine
            client-secret: '{cipher}3fdc092d7bd28cc341871599df348b32408c64aa078c3ef86486c16d2e093072'
            authorization-grant-type: client_credentials
          portalasig_client:
            client-id: portalasig_client
            client-secret: '{cipher}3fdc092d7bd28cc341871599df348b32408c64aa078c3ef86486c16d2e093072'
            authorization-grant-type: password
            token-uri: ${backend-uri}/oauth/token
            scope: openid,profile,email,phone,address
        provider:
          portalasig_engine:
            token-uri: ${portalasig.uaa.ms.url}/oauth2/token
          portalasig_client:
            token-uri: ${portalasig.uaa.ms.url}/oauth2/token
            authorization-uri: ${portalasig.uaa.ms.url}/oauth2/authorize

backend-uri: http://localhost
portalasig.security.auth-server-url: http://ms-uaa:5860/portalasig/uaa
frontend-uri: http://localhost

portalasig.security.oauth2.authorization-server.jwt.issuer-uri: ${backend-uri}:5860/portalasig/uaa
portalasig.uaa.ms:
  v1.url: ${backend-uri}:5860/portalasig/uaa/v1
  url: ${backend-uri}:5860/portalasig/uaa
portalasig.notify.ms:
  v1.url: ${backend-uri}:5862/portalasig/notify/v1
  url: ${backend-uri}:5862/portalasig/notify
portalasig.fe:
  url: ${frontend-uri}:8080