server:
  servlet.context-path: /portalasig/uaa
  port: 5860

spring:
  config.activate.on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:11110/sstest
    username: root
    password: '{cipher}1529ad7e08b0d8355910f239ad1571e5953f6aaf718e1cc9c91a9fc9da346eb6'
  flyway:
    user: root
    password: '{cipher}1529ad7e08b0d8355910f239ad1571e5953f6aaf718e1cc9c91a9fc9da346eb6'
    schemas: sstest
    locations: classpath:db/migration
    url: jdbc:mysql://localhost:11110/

ms:
  uaa:
    tools:
      users:
        csv:
          input-header: name, lastname, email, identity_card, created_at, updated_at, role, active