server:
  servlet.context-path: /portalasig/notify
  port: 5862

spring:
  config.activate.on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:11020/patest
    username: root
    password: '{cipher}3fdc092d7bd28cc341871599df348b32408c64aa078c3ef86486c16d2e093072'
  flyway:
    user: root
    password: '{cipher}3fdc092d7bd28cc341871599df348b32408c64aa078c3ef86486c16d2e093072'
    schemas: patest
    locations: classpath:db/migration
    url: jdbc:mysql://localhost:11020/
  mail:
    host: smtp.gmail.com
    port: 587
    username: '271303085597-t66mljr5ffkbatd6u3ni2mvlohef3mli.apps.googleusercontent.com'
    password: '{cipher}c4bc789e36cb6c56e06488b9cde05f86d4d8fe045650477b7e87fc35473015f2c0194b98c8a1fcbd92f710d5ec8325a9a3c18c70d2597534083db6de70298610'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

portalasig:
  notify:
    email:
      debug:
        enabled: true
        recipient: frankponte95@gmail.com