server:
  servlet.context-path: /portalasig/notify
  port: 5862

spring:
  application.name: portalasig-ms-notify
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-notify:3306/patest
    username: root
    password: '{cipher}3fdc092d7bd28cc341871599df348b32408c64aa078c3ef86486c16d2e093072'
  flyway:
    user: root
    password: '{cipher}3fdc092d7bd28cc341871599df348b32408c64aa078c3ef86486c16d2e093072'
    schemas: patest
    locations: classpath:db/migration
    url: jdbc:mysql://mysql-notify:3306/patest
  mail:
    host: mailhog
    port: 1025
    username: 'portaldeasignaturastest@gmail.com'
    password: '{cipher}ab28ca9278a9d2a2f869ae87cbe605fc020e7363641f7df2f8a8e3341f2cb8203153dc56fda4845fa00db7d32fa51728'
    properties:
      mail:
        debug: true
        smtp:
          auth: false
          starttls:
            enable: false
            required: false
          ssl:
            enable: false
          connectiontimeout: 20000
          timeout: 20000
          writetimeout: 20000
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:5860/portalasig/uaa

portalasig:
  security:
    jwk-set-uri: http://ms-uaa:5860/portalasig/uaa/oauth2/jwks
  notify:
    email:
      debug:
        enabled: true
        recipient: frankponte95@gmail.com
