server:
  servlet.context-path: /portalasig/uaa
  port: 5860

spring:
  application.name: portalasig-ms-uaa
  config.activate.on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:11110/patest
    username: root
    password: '{cipher}3fdc092d7bd28cc341871599df348b32408c64aa078c3ef86486c16d2e093072'
  flyway:
    user: root
    password: '{cipher}3fdc092d7bd28cc341871599df348b32408c64aa078c3ef86486c16d2e093072'
    schemas: patest
    locations: classpath:db/migration
    url: jdbc:mysql://localhost:11110/
  jpa:
    properties.hibernate:
      jdbc.batch_size: 50
      order_inserts: true
      order_updates: true

ms.uaa:
  password-grant.default-client-id: portalasig_client
  tools:
    users:
      csv:
        input-header: name, lastname, email, identity_card, created_at, updated_at, role, active
      default-password: '{cipher}3fdc092d7bd28cc341871599df348b32408c64aa078c3ef86486c16d2e093072'

spring:
  security:
    oauth2:
      authorizationserver:
        issuer: http://ms-uaa:5860/portalasig/uaa
