server:
  servlet.context-path: /portalasig/site
  port: 5861

spring:
  application.name: portalasig-ms-site
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-site:3306/patest
    username: root
    password: '{cipher}3fdc092d7bd28cc341871599df348b32408c64aa078c3ef86486c16d2e093072'
  flyway:
    user: root
    password: '{cipher}3fdc092d7bd28cc341871599df348b32408c64aa078c3ef86486c16d2e093072'
    schemas: patest
    locations: classpath:db/migration
    url: jdbc:mysql://mysql-site:3306/patest
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://ms-uaa:5860/portalasig/uaa

portalasig.security:
  jwk-set-uri: http://ms-uaa:5860/portalasig/uaa/oauth2/jwks

site:
  semester:
    default-creation-status: true
  tools:
    courses:
      csv:
        input-header: code, name, credit_units, type, requirements, careers, course_level
    students:
      import:
        input-header: NRO, LICENCIATURA, CEDULA, NOMBRES, APELLIDOS, CORREO, ESTADO
        email-blacklist: correo@servidor.com
